fix: update action

diff --git a/.github/workflows/flutter-analysis.yaml b/.github/workflows/flutter-analysis.yaml
--- a/.github/workflows/flutter-analysis.yaml
+++ b/.github/workflows/flutter-analysis.yaml
@@ -24,11 +24,11 @@ jobs:
       - name: Run Flutter Analyze
         id: analyze
         run: |
-          OUTPUT=$(flutter analyze)
+          OUTPUT=$(flutter analyze) || true  # Use '|| true' to ensure the command doesn't fail
           echo "Flutter Analyze Output:"
           echo "$OUTPUT"
           echo "::set-output name=analyze_output::$OUTPUT"
-        continue-on-error: true
+        # continue-on-error: true
 
       - name: Comment on PR for each issue
         run: |
